### ISSUE TITLE
Adding an heroku account oauth redirects back to localhost:3000 instead of my configured url

### ISSUE THREAD

**Issue by morkeleb** [Strider-CD/strider-heroku#1]
callback url becomes: http://localhost:3000/ext/heroku/oauth/callback?code=

Adding through Account/Heroku/Add Account

If I change the url in the callback for the browser I get a set of private and public keys.

**Comment by tylermauthe** [comment]
For me, this was the solution... I was using OAUTH_ID and OAUTH_SECRET...

heroku config:add PLUGIN_HEROKU_CLIENT_ID=<CLIENT_ID_FROM_HEROKU> PLUGIN_HEROKU_CLIENT_SECRET=<CLIENT_SECRET_FROM_HEROKU>
