### ISSUE TITLE
Add a Heroku account with Error: Failed to add ssh key

### ISSUE THREAD

**Issue by josefwijaya** [Strider-CD/strider-heroku#15]
After successfully running strider and log in and then trying to add a Heroku account. After login to the heroku account and accept the authorization process it will redirect back and show error as shown in the picture.

in this case, I have set up the environment variables such as
DB_URI=mongodb://.....
PLUGIN_HEROKU_CLIENT_ID=....
PLUGIN_HEROKU_CLIENT_SECRET=....

![image](https://cloud.githubusercontent.com/assets/18253945/26394065/5db7be1e-409e-11e7-96e5-3576ed526d7d.png)

**Comment by knownasilya** [comment]
Resolved in Strider 2.4.5

Requires heroku cli and for you to run `heroku login` before keys can be added.
